// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function DeleteAllChats():Promise<void>;

export function DeleteChat(arg1:string):Promise<void>;

export function DeleteWorkspaceEntry(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetStorageSnapshot():Promise<storage.Snapshot>;

export function LoadChats():Promise<Array<Record<string, any>>>;

export function LoadReplyPreferences():Promise<Array<Record<string, any>>>;

export function OpenWorkspaceInExplorer(arg1:string):Promise<void>;

export function PickWorkspaceDirectory():Promise<Record<string, any>>;

export function ReplaceReplyPreferences(arg1:Array<Record<string, any>>):Promise<void>;

export function SaveAppSettings(arg1:storage.AppSettings):Promise<void>;

export function SaveChat(arg1:Record<string, any>):Promise<void>;

export function SaveWorkspaces(arg1:Array<Record<string, any>>):Promise<void>;

export function ScanWorkspace(arg1:string):Promise<Record<string, any>>;

export function SeedFromBrowser(arg1:storage.Snapshot):Promise<boolean>;

export function CreateWorkspaceDirectory(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function WriteWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
